# Principle Component Analysis

In [22]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_iris

from numpy.polynomial import Polynomial

In [5]:
iris_data = load_iris()
df = pd.DataFrame(iris_data.data,columns= iris_data.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [6]:
df.corr()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.117570           0.871754   
sepal width (cm)           -0.117570          1.000000          -0.428440   
petal length (cm)           0.871754         -0.428440           1.000000   
petal width (cm)            0.817941         -0.366126           0.962865   

                   petal width (cm)  
sepal length (cm)          0.817941  
sepal width (cm)          -0.366126  
petal length (cm)          0.962865  
petal width (cm)           1.000000

In [8]:
df.cov()# spread +Direction

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           0.685694         -0.042434           1.274315   
sepal width (cm)           -0.042434          0.189979          -0.329656   
petal length (cm)           1.274315         -0.329656           3.116278   
petal width (cm)            0.516271         -0.121639           1.295609   

                   petal width (cm)  
sepal length (cm)          0.516271  
sepal width (cm)          -0.121639  
petal length (cm)          1.295609  
petal width (cm)           0.581006

# Eigen Decomposition

There are two type are follow
1)Eigen Values
2)Eigen Vectors

# Roots

In [24]:
# x^2-5x-6
p1 = Polynomial([-6,-5,-1])
p1.roots()

array([-3., -2.])

In [25]:
cov_matrix = df.cov()
cov_matrix

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           0.685694         -0.042434           1.274315   
sepal width (cm)           -0.042434          0.189979          -0.329656   
petal length (cm)           1.274315         -0.329656           3.116278   
petal width (cm)            0.516271         -0.121639           1.295609   

                   petal width (cm)  
sepal length (cm)          0.516271  
sepal width (cm)          -0.121639  
petal length (cm)          1.295609  
petal width (cm)           0.581006

In [27]:
eigvalues = np.linalg.eigvals(cov_matrix)
eigvalues

array([4.22824171, 0.24267075, 0.0782095 , 0.02383509])

In [32]:
eigvalues,eigvectors = np.linalg.eig(cov_matrix)


In [34]:
eigvalues

array([4.22824171, 0.24267075, 0.0782095 , 0.02383509])

In [36]:
eigvectors

array([[ 0.36138659, -0.65658877, -0.58202985,  0.31548719],
       [-0.08452251, -0.73016143,  0.59791083, -0.3197231 ],
       [ 0.85667061,  0.17337266,  0.07623608, -0.47983899],
       [ 0.3582892 ,  0.07548102,  0.54583143,  0.75365743]])

In [38]:
eigvectors[0]

array([ 0.36138659, -0.65658877, -0.58202985,  0.31548719])

In [40]:
eignvectors[1]

array([-0.08452251, -0.73016143,  0.59791083, -0.3197231 ])

In [42]:
eigvectors[2]

array([ 0.85667061,  0.17337266,  0.07623608, -0.47983899])

In [43]:
eigvectors[3]

array([0.3582892 , 0.07548102, 0.54583143, 0.75365743])

In [45]:
eigvectors.shape

(4, 4)

In [47]:
eigvectors.view()

array([[ 0.36138659, -0.65658877, -0.58202985,  0.31548719],
       [-0.08452251, -0.73016143,  0.59791083, -0.3197231 ],
       [ 0.85667061,  0.17337266,  0.07623608, -0.47983899],
       [ 0.3582892 ,  0.07548102,  0.54583143,  0.75365743]])

In [50]:
eigvalues.base

array([4.22824171+0.j, 0.24267075+0.j, 0.0782095 +0.j, 0.02383509+0.j])

In [53]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_diabetes

from numpy.polynomial import Polynomial


In [54]:
dbt_data = load_diabetes()
df = pd.DataFrame(dbt_data.data ,columns=dbt_data.feature_names)
df

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017282 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081414  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019908 -0.017646  
1   -0.039493 -0.068330 -0.092204  
2   -0.002592  0.002864 -0.025930  
3    0.034309  0.022692 -0.009362  
4   -0.002592 -0.031991 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018118  0.044485  
439 -0.011080 -0.046879  0.015491  
440  0.026560  0.044528 -0.025930  
441 -0.039493 -0.004220  0.003064  

[442 rows x 10 columns]

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
dtypes: float64(10)
memory usage: 34.7 KB


In [56]:
df.corr()

age       sex       bmi        bp        s1        s2        s3  \
age  1.000000  0.173737  0.185085  0.335427  0.260061  0.219243 -0.075181   
sex  0.173737  1.000000  0.088161  0.241013  0.035277  0.142637 -0.379090   
bmi  0.185085  0.088161  1.000000  0.395415  0.249777  0.261170 -0.366811   
bp   0.335427  0.241013  0.395415  1.000000  0.242470  0.185558 -0.178761   
s1   0.260061  0.035277  0.249777  0.242470  1.000000  0.896663  0.051519   
s2   0.219243  0.142637  0.261170  0.185558  0.896663  1.000000 -0.196455   
s3  -0.075181 -0.379090 -0.366811 -0.178761  0.051519 -0.196455  1.000000   
s4   0.203841  0.332115  0.413807  0.257653  0.542207  0.659817 -0.738493   
s5   0.270777  0.149918  0.446159  0.393478  0.515501  0.318353 -0.398577   
s6   0.301731  0.208133  0.388680  0.390429  0.325717  0.290600 -0.273697   

           s4        s5        s6  
age  0.203841  0.270777  0.301731  
sex  0.332115  0.149918  0.208133  
bmi  0.413807  0.446159  0.388680  
bp   0.257653  0.393478  0.390429  
s1   0.542207  0.515501  0.325717  
s2   0.659817  0.318353  0.290600  
s3  -0.738493 -0.398577 -0.273697  
s4   1.000000  0.617857  0.417212  
s5   0.617857  1.000000  0.464670  
s6   0.417212  0.464670  1.000000

In [57]:
df.cov()

age       sex       bmi        bp        s1        s2        s3  \
age  0.002268  0.000394  0.000420  0.000761  0.000590  0.000497 -0.000170   
sex  0.000394  0.002268  0.000200  0.000547  0.000080  0.000323 -0.000860   
bmi  0.000420  0.000200  0.002268  0.000897  0.000566  0.000592 -0.000832   
bp   0.000761  0.000547  0.000897  0.002268  0.000550  0.000421 -0.000405   
s1   0.000590  0.000080  0.000566  0.000550  0.002268  0.002033  0.000117   
s2   0.000497  0.000323  0.000592  0.000421  0.002033  0.002268 -0.000445   
s3  -0.000170 -0.000860 -0.000832 -0.000405  0.000117 -0.000445  0.002268   
s4   0.000462  0.000753  0.000938  0.000584  0.001229  0.001496 -0.001675   
s5   0.000614  0.000340  0.001012  0.000892  0.001169  0.000722 -0.000904   
s6   0.000684  0.000472  0.000881  0.000885  0.000739  0.000659 -0.000621   

           s4        s5        s6  
age  0.000462  0.000614  0.000684  
sex  0.000753  0.000340  0.000472  
bmi  0.000938  0.001012  0.000881  
bp   0.000584  0.000892  0.000885  
s1   0.001229  0.001169  0.000739  
s2   0.001496  0.000722  0.000659  
s3  -0.001675 -0.000904 -0.000621  
s4   0.002268  0.001401  0.000946  
s5   0.001401  0.002268  0.001054  
s6   0.000946  0.001054  0.002268

# Roots

In [59]:
p1 =Polynomial([-4,-5,3])
p1.roots()

array([-0.59066729,  2.25733396])

In [60]:
cov_matrix = df.cov()
cov_matrix

age       sex       bmi        bp        s1        s2        s3  \
age  0.002268  0.000394  0.000420  0.000761  0.000590  0.000497 -0.000170   
sex  0.000394  0.002268  0.000200  0.000547  0.000080  0.000323 -0.000860   
bmi  0.000420  0.000200  0.002268  0.000897  0.000566  0.000592 -0.000832   
bp   0.000761  0.000547  0.000897  0.002268  0.000550  0.000421 -0.000405   
s1   0.000590  0.000080  0.000566  0.000550  0.002268  0.002033  0.000117   
s2   0.000497  0.000323  0.000592  0.000421  0.002033  0.002268 -0.000445   
s3  -0.000170 -0.000860 -0.000832 -0.000405  0.000117 -0.000445  0.002268   
s4   0.000462  0.000753  0.000938  0.000584  0.001229  0.001496 -0.001675   
s5   0.000614  0.000340  0.001012  0.000892  0.001169  0.000722 -0.000904   
s6   0.000684  0.000472  0.000881  0.000885  0.000739  0.000659 -0.000621   

           s4        s5        s6  
age  0.000462  0.000614  0.000684  
sex  0.000753  0.000340  0.000472  
bmi  0.000938  0.001012  0.000881  
bp   0.000584  0.000892  0.000885  
s1   0.001229  0.001169  0.000739  
s2   0.001496  0.000722  0.000659  
s3  -0.001675 -0.000904 -0.000621  
s4   0.002268  0.001401  0.000946  
s5   0.001401  0.002268  0.001054  
s6   0.000946  0.001054  0.002268

In [68]:
eigvalues = np.linalg.eigvals(cov_matrix)
eigvalues

array([9.12520221e-03, 3.38394158e-03, 2.73460842e-03, 2.16661312e-03,
       1.94116324e-05, 1.77596168e-04, 1.50155460e-03, 9.83408623e-04,
       1.36671023e-03, 1.21669038e-03])

In [65]:
eigvalues,eigvectors = np.linalg.eig(cov_matrix)

In [66]:
eigvalues


array([9.12520221e-03, 3.38394158e-03, 2.73460842e-03, 2.16661312e-03,
       1.94116324e-05, 1.77596168e-04, 1.50155460e-03, 9.83408623e-04,
       1.36671023e-03, 1.21669038e-03])

In [67]:
eigvectors

array([[-0.21643101, -0.04437151, -0.49466811,  0.4140095 ,  0.00326309,
         0.00810057,  0.68686389, -0.01493468, -0.2258505 ,  0.10953821],
       [-0.18696711,  0.38654811,  0.10685833,  0.67986052,  0.00366069,
        -0.00210552, -0.37345612, -0.44293966,  0.04173103,  0.06760551],
       [-0.3031625 ,  0.15628061, -0.1675317 , -0.49982533,  0.00824809,
         0.04237751, -0.12935936, -0.39294187, -0.4031419 ,  0.51985787],
       [-0.2717397 ,  0.13825564, -0.51356804,  0.01966734, -0.00322111,
         0.0271941 , -0.48689014,  0.47736435, -0.27276274, -0.32064908],
       [-0.34325493, -0.57302669,  0.0685867 ,  0.06839533,  0.70977447,
        -0.04203984, -0.12917415, -0.12941351,  0.00540864, -0.07364908],
       [-0.35186062, -0.45593985,  0.26969438,  0.16777384, -0.56319605,
        -0.35931549, -0.11673143,  0.19131121, -0.1332572 ,  0.23054011],
       [ 0.28243639, -0.50624287, -0.38602787,  0.07602005, -0.31744413,
         0.48124771, -0.24499115, -0.32463641

In [70]:
eigvalues[0]

0.00912520221242393

In [71]:
eigvectors[0]

array([-0.21643101, -0.04437151, -0.49466811,  0.4140095 ,  0.00326309,
        0.00810057,  0.68686389, -0.01493468, -0.2258505 ,  0.10953821])

In [73]:
eigvectors.shape

(10, 10)